/*
 * Copyright (c) 2024 Max Lemberg. This file is part of ChessMax.
 * Licenced under the CC BY-NC 4.0 License.
 * See "http://creativecommons.org/licenses/by-nc/4.0/".
 */

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mlprograms.chess.account.ui;

import com.mlprograms.chess.utils.WindowPositionManager;

import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;

/**
 *
 * @author maxle
 */
public class Startmenu extends javax.swing.JFrame {

    private final WindowPositionManager positionManager;

    /**
     * Creates new form LoginUI
     */
    public Startmenu() {
        positionManager = new WindowPositionManager(this);
        initComponents();
        positionManager.loadPosition();

        addComponentListener(new ComponentAdapter() {
            @Override
            public void componentMoved(ComponentEvent e) {
                positionManager.savePosition();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startmenueTitle = new javax.swing.JLabel();
        jButtonLoginAndRegistration = new javax.swing.JButton();
        jButtonPatchNotes = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jButtonPlayAsGuest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        startmenueTitle.setFont(new java.awt.Font("Malgun Gothic", 0, 24)); // NOI18N
        startmenueTitle.setText("Startseite");
        startmenueTitle.setToolTipText("");
        startmenueTitle.setAlignmentX(1.0F);
        startmenueTitle.setAlignmentY(1.0F);
        startmenueTitle.setFocusable(false);
        startmenueTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonLoginAndRegistration.setText("Anmelden / Registrieren");
        jButtonLoginAndRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginAndRegistrationActionPerformed(evt);
            }
        });

        jButtonPatchNotes.setText("Versionshinweise");

        jButtonSettings.setText("Einstellungen");

        jButtonPlayAsGuest.setText("Als Gast spielen");
        jButtonPlayAsGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlayAsGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLoginAndRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPatchNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlayAsGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(150, Short.MAX_VALUE)
                    .addComponent(startmenueTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(150, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButtonLoginAndRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPlayAsGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPatchNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(12, Short.MAX_VALUE)
                    .addComponent(startmenueTitle)
                    .addContainerGap(236, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLoginAndRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginAndRegistrationActionPerformed
        this.dispose();
		  new Login().setVisible(true);
    }//GEN-LAST:event_jButtonLoginAndRegistrationActionPerformed

    private void jButtonPlayAsGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlayAsGuestActionPerformed
        // TODO add your handling code here: start game against bot
    }//GEN-LAST:event_jButtonPlayAsGuestActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLoginAndRegistration;
    private javax.swing.JButton jButtonPatchNotes;
    private javax.swing.JButton jButtonPlayAsGuest;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JLabel startmenueTitle;
    // End of variables declaration//GEN-END:variables
}
